/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sistema.login.mongo;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.Mongo;
import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author PICHAU
 */
public class LoginFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public LoginFrame() {
        initComponents();
        txtSenhaRegistro.setVisible(false);
        txtEmailRegistro.setVisible(false);
        txtNomeRegistro.setVisible(false);
        btnRegistro.setVisible(false);
        btnDeslogar.setVisible(false);
        lblLogado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_email_login = new javax.swing.JTextField();
        pswd_senha_login = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblLogado = new javax.swing.JLabel();
        btnDeslogar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtNomeRegistro = new javax.swing.JTextField();
        txtSenhaRegistro = new javax.swing.JTextField();
        txtEmailRegistro = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();

        setBorder(null);

        txt_email_login.setToolTipText("Email");
        txt_email_login.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_email_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_loginActionPerformed(evt);
            }
        });

        pswd_senha_login.setToolTipText("Senha");

        btnLogin.setText("Entrar");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        lblLogado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblLogado.setText("Parabéns! Você está logado!");

        btnDeslogar.setText("deslogar");
        btnDeslogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeslogarMousePressed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarMousePressed(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtNomeRegistro.setText("Nome");

        txtSenhaRegistro.setText("Senha");

        txtEmailRegistro.setText("Email");

        btnRegistro.setText("Registrar");
        btnRegistro.setToolTipText("");
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistroMousePressed(evt);
            }
        });
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSenhaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(btnDeslogar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(lblLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pswd_senha_login, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(331, 331, 331))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(283, 283, 283))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(391, 391, 391))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(365, 365, 365))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeslogar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txt_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswd_senha_login, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_email_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_email_loginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        String email;
        char[] senhaAux = new char[100]; 
        String senha;
        char[] senhaSalva = new char[100];
        
        email = txt_email_login.getText();
        senhaAux = pswd_senha_login.getPassword();
        
        senha = String.valueOf(senhaAux);
        Mongo mongo = new Mongo("localhost",27017);
        DB db = mongo.getDB("sistemaLogin");
        
        DBCollection collection = db.getCollection("usuario");
        
        BasicDBObject where = new BasicDBObject();
        where.put("email",email);
        DBCursor Cursor = collection.find(where);
     
        if(Cursor.hasNext()){
            List<DBObject> usuario = Cursor.toArray();
            String aux = usuario.toString();
            String[] dbDataAux = aux.split(",");
            String[] dbDataEmail = dbDataAux[2].split(":");
            dbDataEmail[1] = dbDataEmail[1].substring(1, dbDataEmail[1].length()-1);
            dbDataEmail[1] = dbDataEmail[1].substring(1, dbDataEmail[1].length()-1);
            System.out.println(dbDataEmail[1]);
            System.out.println(email);
            System.out.println(dbDataEmail[1].equals(email));
            if(dbDataEmail[1].equals(email)){
                String[] dbDataSenha = dbDataAux[3].split(":");   
                dbDataSenha[1] = dbDataSenha[1].substring(1, dbDataSenha[1].length()-1);
                dbDataSenha[1] = dbDataSenha[1].substring(1, dbDataSenha[1].length()-1);
                dbDataSenha[1] = dbDataSenha[1].substring(0, dbDataSenha[1].length()-1);
                System.out.println(senha);
                System.out.println(dbDataSenha[1]);
                System.out.println(dbDataSenha[1].equals(senha));
                System.out.println(dbDataSenha[1]);
                if(dbDataSenha[1].equals(senha)){
                    txtSenhaRegistro.setVisible(false);
                    txtEmailRegistro.setVisible(false);
                    txtNomeRegistro.setVisible(false);
                    btnRegistro.setVisible(false);
                    btnLogin.setVisible(false);
                    txt_email_login.setVisible(false);
                    pswd_senha_login.setVisible(false);
                    btnRegistrar.setVisible(false);
                    
                    
                    janela.trocaLogin();
                    
                    
                    lblLogado.setVisible(true);
                    btnDeslogar.setVisible(true);
                }  
            }
            else{
            JOptionPane.showMessageDialog(null, "A senha Inseria não é válida!", "Senha Inválida!", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "O Email inserido não é válido!", "Email inválido!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnDeslogarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeslogarMousePressed
        // TODO add your handling code here:
        btnLogin.setVisible(true);
        txt_email_login.setVisible(true);
        pswd_senha_login.setVisible(true);
        btnRegistrar.setVisible(true);
        
         janela.trocaLogin();
            
        txtSenhaRegistro.setVisible(false);
        txtEmailRegistro.setVisible(false);
        txtNomeRegistro.setVisible(false);
        btnRegistro.setVisible(false);
        lblLogado.setVisible(false);
        btnDeslogar.setVisible(false);
        
    }//GEN-LAST:event_btnDeslogarMousePressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMousePressed
        // TODO add your handling code here:
        lblLogado.setVisible(false);
        btnDeslogar.setVisible(false);
        btnLogin.setVisible(false);
        txt_email_login.setVisible(false);
        pswd_senha_login.setVisible(false);
        btnRegistrar.setVisible(false);
        
        txtSenhaRegistro.setVisible(true);
        txtEmailRegistro.setVisible(true);
        txtNomeRegistro.setVisible(true);
        btnRegistro.setVisible(true);
        
    }//GEN-LAST:event_btnRegistrarMousePressed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMousePressed
//         TODO add your handling code here:
        
                    
        String nome = txtNomeRegistro.getText();
        String email = txtEmailRegistro.getText();
        String senha = txtSenhaRegistro.getText();
        
        int flag = email.indexOf('@');
        if(flag < 0){
            JOptionPane.showMessageDialog(null, "O Email inserido não é válido!", "Email inválido!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            MongoClient cliente = new MongoClient();
            MongoDatabase bancoDeDados = cliente.getDatabase("sistemaLogin");
            MongoCollection<Document> usuarios = bancoDeDados.getCollection("usuario");
            
            Document novoregistro = new Document("nome" , nome);
            novoregistro.append("email",email);
            novoregistro.append("senha",senha);
            
            usuarios.insertOne(novoregistro);
            
            cliente.close();  
            
            txtSenhaRegistro.setVisible(false);
            txtEmailRegistro.setVisible(false);
            txtNomeRegistro.setVisible(false);
            btnRegistro.setVisible(false);

            lblLogado.setVisible(true);
            btnDeslogar.setVisible(true);

            janela.trocaLogin();
        }
       
    }//GEN-LAST:event_btnRegistroMousePressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel lblLogado;
    private javax.swing.JPasswordField pswd_senha_login;
    private javax.swing.JTextField txtEmailRegistro;
    private javax.swing.JTextField txtNomeRegistro;
    private javax.swing.JTextField txtSenhaRegistro;
    private javax.swing.JTextField txt_email_login;
    // End of variables declaration//GEN-END:variables
}
